// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMselOqvWrv290OUBApKvGqoKzlsymBwA',
    appId: '1:1021413241242:android:9753f892e983ebcb1f0a23',
    messagingSenderId: '1021413241242',
    projectId: 'eco-bin-8a044',
    databaseURL: 'https://eco-bin-8a044-default-rtdb.firebaseio.com',
    storageBucket: 'eco-bin-8a044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDja6knaHz0L7ayVI9J_e5FhTQq-MmoAw',
    appId: '1:1021413241242:ios:beb785efe5048e641f0a23',
    messagingSenderId: '1021413241242',
    projectId: 'eco-bin-8a044',
    databaseURL: 'https://eco-bin-8a044-default-rtdb.firebaseio.com',
    storageBucket: 'eco-bin-8a044.firebasestorage.app',
    iosBundleId: 'com.example.mastersFinalApp',
  );
}
